version: "3.7"

services:
  spring_boot_api:
    image: dobemcontabilidade/erpdobemcontabilidade:latest
    networks:
      - minha_rede
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - DB_POSTGRESDB_DATABASE=erpDobemcontabilidade
      - DB_POSTGRESDB_HOST=servidordigitalocean.dobemcontabilidade.com
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=AdminAdmin
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.spring_boot_api.rule=Host(`erpdobem.dobemcontabilidade.com`)
        - traefik.http.routers.spring_boot_api.entrypoints=websecure
        - traefik.http.routers.spring_boot_api.priority=1
        - traefik.http.routers.spring_boot_api.tls.certresolver=letsencryptresolver
        - traefik.http.routers.spring_boot_api.service=spring_boot_api
        - traefik.http.services.spring_boot_api.loadbalancer.server.port=8080
        - traefik.http.services.spring_boot_api.loadbalancer.passHostHeader=1

networks:
  minha_rede:
    name: minha_rede
    external: true
