version: "3.7"

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: erpDobemcontabilidade
            POSTGRES_USER: erpDobemcontabilidade
            POSTGRES_PASSWORD: senhaSegura
        # remove the "127.0.0.1:" prefix
        ports:
            - 127.0.0.1:5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - pgnetwork

    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@dobemcontabilidade.com
            PGADMIN_DEFAULT_PASSWORD: senhaAdmin
        ports:
            - "9000:80"
        depends_on:
            - db
        networks:
            - pgnetwork
    api-erp:
     image: dobemcontabilidade/erpdobemcontabilidade:latest
     environment:
       - SPRING_PROFILES_ACTIVE=dev
       - SERVER_PORT=8080
       - DB_POSTGRESDB_DATABASE=erpDobemcontabilidade
       - DB_POSTGRESDB_HOST=127.0.0.1
       - DB_POSTGRESDB_PORT=5432
       - DB_POSTGRESDB_USER=erpDobemcontabilidade
       - DB_POSTGRESDB_PASSWORD=senhaSegura
     ports:
       - "8080:8080"
     depends_on:
        - db
     networks:
        - pgnetwork
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints:
           - node.role == manager
       resources:
         limits:
           cpus: "0.5"
           memory: 1024M

networks:
    pgnetwork:
        driver: bridge

volumes:
    pgdata:
