export enum DiasDaSemanaEnum {
  SEGUNDAFEIRA = 'SEGUNDAFEIRA',

  TERCAFEIRA = 'TERCAFEIRA',

  QUARTAFEIRA = 'QUARTAFEIRA',

  QUINTAFEIRA = 'QUINTAFEIRA',

  SEXTAFEIRA = 'SEXTAFEIRA',

  SABADO = 'SABADO',

  DOMINGO = 'DOMINGO',
}
