export enum PessoaComDeficienciaEnum {
  DEFICIENCIAMOTORA = 'DEFICIENCIAMOTORA',

  DEFICIENCIAVISUAL = 'DEFICIENCIAVISUAL',

  DEFICIENCIAAUDITIVA = 'DEFICIENCIAAUDITIVA',

  REABILITADO = 'REABILITADO',

  NAOPOSSUI = 'NAOPOSSUI',
}
