export enum SituacaoDemissaoEnum {
  SOLICITADO = 'SOLICITADO',

  GERADO = 'GERADO',

  DEMISSAOEMANDAMENTO = 'DEMISSAOEMANDAMENTO',

  EMANDAMENTO = 'EMANDAMENTO',

  CANCELADO = 'CANCELADO',

  REMOVIDO = 'REMOVIDO',

  FINALIZADO = 'FINALIZADO',

  ABERTO = 'ABERTO',

  PAGO = 'PAGO',
}
