export enum TipoDemissaoEnum {
  JUSTACAUSA = 'JUSTACAUSA',

  DESPEDIDASEMJUSTACAUSA = 'DESPEDIDASEMJUSTACAUSA',

  RECISAOANTECIPADA = 'RECISAOANTECIPADA',

  FALECIMENTOEMPREGADO = 'FALECIMENTOEMPREGADO',

  PEDIDO = 'PEDIDO',

  CONSENSUAL = 'CONSENSUAL',

  ACORDO = 'ACORDO',
}
