package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AgendaTarefaOrdemServicoExecucaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendaTarefaOrdemServicoExecucaoAllPropertiesEquals(
        AgendaTarefaOrdemServicoExecucao expected,
        AgendaTarefaOrdemServicoExecucao actual
    ) {
        assertAgendaTarefaOrdemServicoExecucaoAutoGeneratedPropertiesEquals(expected, actual);
        assertAgendaTarefaOrdemServicoExecucaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendaTarefaOrdemServicoExecucaoAllUpdatablePropertiesEquals(
        AgendaTarefaOrdemServicoExecucao expected,
        AgendaTarefaOrdemServicoExecucao actual
    ) {
        assertAgendaTarefaOrdemServicoExecucaoUpdatableFieldsEquals(expected, actual);
        assertAgendaTarefaOrdemServicoExecucaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendaTarefaOrdemServicoExecucaoAutoGeneratedPropertiesEquals(
        AgendaTarefaOrdemServicoExecucao expected,
        AgendaTarefaOrdemServicoExecucao actual
    ) {
        assertThat(expected)
            .as("Verify AgendaTarefaOrdemServicoExecucao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendaTarefaOrdemServicoExecucaoUpdatableFieldsEquals(
        AgendaTarefaOrdemServicoExecucao expected,
        AgendaTarefaOrdemServicoExecucao actual
    ) {
        assertThat(expected)
            .as("Verify AgendaTarefaOrdemServicoExecucao relevant properties")
            .satisfies(e -> assertThat(e.getHoraInicio()).as("check horaInicio").isEqualTo(actual.getHoraInicio()))
            .satisfies(e -> assertThat(e.getHoraFim()).as("check horaFim").isEqualTo(actual.getHoraFim()))
            .satisfies(e -> assertThat(e.getDiaInteiro()).as("check diaInteiro").isEqualTo(actual.getDiaInteiro()))
            .satisfies(e -> assertThat(e.getAtivo()).as("check ativo").isEqualTo(actual.getAtivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgendaTarefaOrdemServicoExecucaoUpdatableRelationshipsEquals(
        AgendaTarefaOrdemServicoExecucao expected,
        AgendaTarefaOrdemServicoExecucao actual
    ) {
        assertThat(expected)
            .as("Verify AgendaTarefaOrdemServicoExecucao relationships")
            .satisfies(
                e ->
                    assertThat(e.getTarefaOrdemServicoExecucao())
                        .as("check tarefaOrdemServicoExecucao")
                        .isEqualTo(actual.getTarefaOrdemServicoExecucao())
            );
    }
}
