package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AgenteIntegracaoEstagioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgenteIntegracaoEstagioAllPropertiesEquals(AgenteIntegracaoEstagio expected, AgenteIntegracaoEstagio actual) {
        assertAgenteIntegracaoEstagioAutoGeneratedPropertiesEquals(expected, actual);
        assertAgenteIntegracaoEstagioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgenteIntegracaoEstagioAllUpdatablePropertiesEquals(
        AgenteIntegracaoEstagio expected,
        AgenteIntegracaoEstagio actual
    ) {
        assertAgenteIntegracaoEstagioUpdatableFieldsEquals(expected, actual);
        assertAgenteIntegracaoEstagioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgenteIntegracaoEstagioAutoGeneratedPropertiesEquals(
        AgenteIntegracaoEstagio expected,
        AgenteIntegracaoEstagio actual
    ) {
        assertThat(expected)
            .as("Verify AgenteIntegracaoEstagio auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgenteIntegracaoEstagioUpdatableFieldsEquals(
        AgenteIntegracaoEstagio expected,
        AgenteIntegracaoEstagio actual
    ) {
        assertThat(expected)
            .as("Verify AgenteIntegracaoEstagio relevant properties")
            .satisfies(e -> assertThat(e.getCnpj()).as("check cnpj").isEqualTo(actual.getCnpj()))
            .satisfies(e -> assertThat(e.getRazaoSocial()).as("check razaoSocial").isEqualTo(actual.getRazaoSocial()))
            .satisfies(e -> assertThat(e.getCoordenador()).as("check coordenador").isEqualTo(actual.getCoordenador()))
            .satisfies(
                e -> assertThat(e.getCpfCoordenadorEstagio()).as("check cpfCoordenadorEstagio").isEqualTo(actual.getCpfCoordenadorEstagio())
            )
            .satisfies(e -> assertThat(e.getLogradouro()).as("check logradouro").isEqualTo(actual.getLogradouro()))
            .satisfies(e -> assertThat(e.getNumero()).as("check numero").isEqualTo(actual.getNumero()))
            .satisfies(e -> assertThat(e.getComplemento()).as("check complemento").isEqualTo(actual.getComplemento()))
            .satisfies(e -> assertThat(e.getBairro()).as("check bairro").isEqualTo(actual.getBairro()))
            .satisfies(e -> assertThat(e.getCep()).as("check cep").isEqualTo(actual.getCep()))
            .satisfies(e -> assertThat(e.getPrincipal()).as("check principal").isEqualTo(actual.getPrincipal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgenteIntegracaoEstagioUpdatableRelationshipsEquals(
        AgenteIntegracaoEstagio expected,
        AgenteIntegracaoEstagio actual
    ) {
        assertThat(expected)
            .as("Verify AgenteIntegracaoEstagio relationships")
            .satisfies(e -> assertThat(e.getCidade()).as("check cidade").isEqualTo(actual.getCidade()));
    }
}
