package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnexoTarefaRecorrenteExecucaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoTarefaRecorrenteExecucaoAllPropertiesEquals(
        AnexoTarefaRecorrenteExecucao expected,
        AnexoTarefaRecorrenteExecucao actual
    ) {
        assertAnexoTarefaRecorrenteExecucaoAutoGeneratedPropertiesEquals(expected, actual);
        assertAnexoTarefaRecorrenteExecucaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoTarefaRecorrenteExecucaoAllUpdatablePropertiesEquals(
        AnexoTarefaRecorrenteExecucao expected,
        AnexoTarefaRecorrenteExecucao actual
    ) {
        assertAnexoTarefaRecorrenteExecucaoUpdatableFieldsEquals(expected, actual);
        assertAnexoTarefaRecorrenteExecucaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoTarefaRecorrenteExecucaoAutoGeneratedPropertiesEquals(
        AnexoTarefaRecorrenteExecucao expected,
        AnexoTarefaRecorrenteExecucao actual
    ) {
        assertThat(expected)
            .as("Verify AnexoTarefaRecorrenteExecucao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoTarefaRecorrenteExecucaoUpdatableFieldsEquals(
        AnexoTarefaRecorrenteExecucao expected,
        AnexoTarefaRecorrenteExecucao actual
    ) {
        assertThat(expected)
            .as("Verify AnexoTarefaRecorrenteExecucao relevant properties")
            .satisfies(e -> assertThat(e.getUrl()).as("check url").isEqualTo(actual.getUrl()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getDataHoraUpload()).as("check dataHoraUpload").isEqualTo(actual.getDataHoraUpload()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoTarefaRecorrenteExecucaoUpdatableRelationshipsEquals(
        AnexoTarefaRecorrenteExecucao expected,
        AnexoTarefaRecorrenteExecucao actual
    ) {
        assertThat(expected)
            .as("Verify AnexoTarefaRecorrenteExecucao relationships")
            .satisfies(
                e ->
                    assertThat(e.getTarefaRecorrenteExecucao())
                        .as("check tarefaRecorrenteExecucao")
                        .isEqualTo(actual.getTarefaRecorrenteExecucao())
            );
    }
}
