package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnexoRequeridoTarefaRecorrenteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoTarefaRecorrenteAllPropertiesEquals(
        AnexoRequeridoTarefaRecorrente expected,
        AnexoRequeridoTarefaRecorrente actual
    ) {
        assertAnexoRequeridoTarefaRecorrenteAutoGeneratedPropertiesEquals(expected, actual);
        assertAnexoRequeridoTarefaRecorrenteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoTarefaRecorrenteAllUpdatablePropertiesEquals(
        AnexoRequeridoTarefaRecorrente expected,
        AnexoRequeridoTarefaRecorrente actual
    ) {
        assertAnexoRequeridoTarefaRecorrenteUpdatableFieldsEquals(expected, actual);
        assertAnexoRequeridoTarefaRecorrenteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoTarefaRecorrenteAutoGeneratedPropertiesEquals(
        AnexoRequeridoTarefaRecorrente expected,
        AnexoRequeridoTarefaRecorrente actual
    ) {
        assertThat(expected)
            .as("Verify AnexoRequeridoTarefaRecorrente auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoTarefaRecorrenteUpdatableFieldsEquals(
        AnexoRequeridoTarefaRecorrente expected,
        AnexoRequeridoTarefaRecorrente actual
    ) {
        assertThat(expected)
            .as("Verify AnexoRequeridoTarefaRecorrente relevant properties")
            .satisfies(e -> assertThat(e.getObrigatorio()).as("check obrigatorio").isEqualTo(actual.getObrigatorio()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoTarefaRecorrenteUpdatableRelationshipsEquals(
        AnexoRequeridoTarefaRecorrente expected,
        AnexoRequeridoTarefaRecorrente actual
    ) {
        assertThat(expected)
            .as("Verify AnexoRequeridoTarefaRecorrente relationships")
            .satisfies(e -> assertThat(e.getAnexoRequerido()).as("check anexoRequerido").isEqualTo(actual.getAnexoRequerido()))
            .satisfies(e -> assertThat(e.getTarefaRecorrente()).as("check tarefaRecorrente").isEqualTo(actual.getTarefaRecorrente()));
    }
}
