package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnexoRequeridoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoAllPropertiesEquals(AnexoRequerido expected, AnexoRequerido actual) {
        assertAnexoRequeridoAutoGeneratedPropertiesEquals(expected, actual);
        assertAnexoRequeridoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoAllUpdatablePropertiesEquals(AnexoRequerido expected, AnexoRequerido actual) {
        assertAnexoRequeridoUpdatableFieldsEquals(expected, actual);
        assertAnexoRequeridoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoAutoGeneratedPropertiesEquals(AnexoRequerido expected, AnexoRequerido actual) {
        assertThat(expected)
            .as("Verify AnexoRequerido auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoUpdatableFieldsEquals(AnexoRequerido expected, AnexoRequerido actual) {
        assertThat(expected)
            .as("Verify AnexoRequerido relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getTipo()).as("check tipo").isEqualTo(actual.getTipo()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoUpdatableRelationshipsEquals(AnexoRequerido expected, AnexoRequerido actual) {}
}
