package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnexoRequeridoServicoContabilAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoServicoContabilAllPropertiesEquals(
        AnexoRequeridoServicoContabil expected,
        AnexoRequeridoServicoContabil actual
    ) {
        assertAnexoRequeridoServicoContabilAutoGeneratedPropertiesEquals(expected, actual);
        assertAnexoRequeridoServicoContabilAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoServicoContabilAllUpdatablePropertiesEquals(
        AnexoRequeridoServicoContabil expected,
        AnexoRequeridoServicoContabil actual
    ) {
        assertAnexoRequeridoServicoContabilUpdatableFieldsEquals(expected, actual);
        assertAnexoRequeridoServicoContabilUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoServicoContabilAutoGeneratedPropertiesEquals(
        AnexoRequeridoServicoContabil expected,
        AnexoRequeridoServicoContabil actual
    ) {
        assertThat(expected)
            .as("Verify AnexoRequeridoServicoContabil auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoServicoContabilUpdatableFieldsEquals(
        AnexoRequeridoServicoContabil expected,
        AnexoRequeridoServicoContabil actual
    ) {
        assertThat(expected)
            .as("Verify AnexoRequeridoServicoContabil relevant properties")
            .satisfies(e -> assertThat(e.getObrigatorio()).as("check obrigatorio").isEqualTo(actual.getObrigatorio()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoServicoContabilUpdatableRelationshipsEquals(
        AnexoRequeridoServicoContabil expected,
        AnexoRequeridoServicoContabil actual
    ) {
        assertThat(expected)
            .as("Verify AnexoRequeridoServicoContabil relationships")
            .satisfies(e -> assertThat(e.getServicoContabil()).as("check servicoContabil").isEqualTo(actual.getServicoContabil()))
            .satisfies(e -> assertThat(e.getAnexoRequerido()).as("check anexoRequerido").isEqualTo(actual.getAnexoRequerido()));
    }
}
