package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnexoPessoaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoPessoaAllPropertiesEquals(AnexoPessoa expected, AnexoPessoa actual) {
        assertAnexoPessoaAutoGeneratedPropertiesEquals(expected, actual);
        assertAnexoPessoaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoPessoaAllUpdatablePropertiesEquals(AnexoPessoa expected, AnexoPessoa actual) {
        assertAnexoPessoaUpdatableFieldsEquals(expected, actual);
        assertAnexoPessoaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoPessoaAutoGeneratedPropertiesEquals(AnexoPessoa expected, AnexoPessoa actual) {
        assertThat(expected)
            .as("Verify AnexoPessoa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoPessoaUpdatableFieldsEquals(AnexoPessoa expected, AnexoPessoa actual) {
        assertThat(expected)
            .as("Verify AnexoPessoa relevant properties")
            .satisfies(e -> assertThat(e.getUrlArquivo()).as("check urlArquivo").isEqualTo(actual.getUrlArquivo()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoPessoaUpdatableRelationshipsEquals(AnexoPessoa expected, AnexoPessoa actual) {
        assertThat(expected)
            .as("Verify AnexoPessoa relationships")
            .satisfies(e -> assertThat(e.getPessoa()).as("check pessoa").isEqualTo(actual.getPessoa()));
    }
}
