package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnexoEmpresaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoEmpresaAllPropertiesEquals(AnexoEmpresa expected, AnexoEmpresa actual) {
        assertAnexoEmpresaAutoGeneratedPropertiesEquals(expected, actual);
        assertAnexoEmpresaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoEmpresaAllUpdatablePropertiesEquals(AnexoEmpresa expected, AnexoEmpresa actual) {
        assertAnexoEmpresaUpdatableFieldsEquals(expected, actual);
        assertAnexoEmpresaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoEmpresaAutoGeneratedPropertiesEquals(AnexoEmpresa expected, AnexoEmpresa actual) {
        assertThat(expected)
            .as("Verify AnexoEmpresa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoEmpresaUpdatableFieldsEquals(AnexoEmpresa expected, AnexoEmpresa actual) {
        assertThat(expected)
            .as("Verify AnexoEmpresa relevant properties")
            .satisfies(e -> assertThat(e.getUrlAnexo()).as("check urlAnexo").isEqualTo(actual.getUrlAnexo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoEmpresaUpdatableRelationshipsEquals(AnexoEmpresa expected, AnexoEmpresa actual) {
        assertThat(expected)
            .as("Verify AnexoEmpresa relationships")
            .satisfies(e -> assertThat(e.getEmpresa()).as("check empresa").isEqualTo(actual.getEmpresa()))
            .satisfies(
                e -> assertThat(e.getAnexoRequeridoEmpresa()).as("check anexoRequeridoEmpresa").isEqualTo(actual.getAnexoRequeridoEmpresa())
            );
    }
}
