package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AnexoRequeridoTarefaOrdemServicoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoTarefaOrdemServicoAllPropertiesEquals(
        AnexoRequeridoTarefaOrdemServico expected,
        AnexoRequeridoTarefaOrdemServico actual
    ) {
        assertAnexoRequeridoTarefaOrdemServicoAutoGeneratedPropertiesEquals(expected, actual);
        assertAnexoRequeridoTarefaOrdemServicoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoTarefaOrdemServicoAllUpdatablePropertiesEquals(
        AnexoRequeridoTarefaOrdemServico expected,
        AnexoRequeridoTarefaOrdemServico actual
    ) {
        assertAnexoRequeridoTarefaOrdemServicoUpdatableFieldsEquals(expected, actual);
        assertAnexoRequeridoTarefaOrdemServicoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoTarefaOrdemServicoAutoGeneratedPropertiesEquals(
        AnexoRequeridoTarefaOrdemServico expected,
        AnexoRequeridoTarefaOrdemServico actual
    ) {
        assertThat(expected)
            .as("Verify AnexoRequeridoTarefaOrdemServico auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoTarefaOrdemServicoUpdatableFieldsEquals(
        AnexoRequeridoTarefaOrdemServico expected,
        AnexoRequeridoTarefaOrdemServico actual
    ) {
        assertThat(expected)
            .as("Verify AnexoRequeridoTarefaOrdemServico relevant properties")
            .satisfies(e -> assertThat(e.getObrigatorio()).as("check obrigatorio").isEqualTo(actual.getObrigatorio()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAnexoRequeridoTarefaOrdemServicoUpdatableRelationshipsEquals(
        AnexoRequeridoTarefaOrdemServico expected,
        AnexoRequeridoTarefaOrdemServico actual
    ) {
        assertThat(expected)
            .as("Verify AnexoRequeridoTarefaOrdemServico relationships")
            .satisfies(e -> assertThat(e.getAnexoRequerido()).as("check anexoRequerido").isEqualTo(actual.getAnexoRequerido()))
            .satisfies(e -> assertThat(e.getTarefaOrdemServico()).as("check tarefaOrdemServico").isEqualTo(actual.getTarefaOrdemServico()));
    }
}
