package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AreaContabilAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaContabilAllPropertiesEquals(AreaContabil expected, AreaContabil actual) {
        assertAreaContabilAutoGeneratedPropertiesEquals(expected, actual);
        assertAreaContabilAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaContabilAllUpdatablePropertiesEquals(AreaContabil expected, AreaContabil actual) {
        assertAreaContabilUpdatableFieldsEquals(expected, actual);
        assertAreaContabilUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaContabilAutoGeneratedPropertiesEquals(AreaContabil expected, AreaContabil actual) {
        assertThat(expected)
            .as("Verify AreaContabil auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaContabilUpdatableFieldsEquals(AreaContabil expected, AreaContabil actual) {
        assertThat(expected)
            .as("Verify AreaContabil relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getPercentual()).as("check percentual").isEqualTo(actual.getPercentual()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAreaContabilUpdatableRelationshipsEquals(AreaContabil expected, AreaContabil actual) {}
}
