package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AtorAvaliadoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAtorAvaliadoAllPropertiesEquals(AtorAvaliado expected, AtorAvaliado actual) {
        assertAtorAvaliadoAutoGeneratedPropertiesEquals(expected, actual);
        assertAtorAvaliadoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAtorAvaliadoAllUpdatablePropertiesEquals(AtorAvaliado expected, AtorAvaliado actual) {
        assertAtorAvaliadoUpdatableFieldsEquals(expected, actual);
        assertAtorAvaliadoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAtorAvaliadoAutoGeneratedPropertiesEquals(AtorAvaliado expected, AtorAvaliado actual) {
        assertThat(expected)
            .as("Verify AtorAvaliado auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAtorAvaliadoUpdatableFieldsEquals(AtorAvaliado expected, AtorAvaliado actual) {
        assertThat(expected)
            .as("Verify AtorAvaliado relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getAtivo()).as("check ativo").isEqualTo(actual.getAtivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAtorAvaliadoUpdatableRelationshipsEquals(AtorAvaliado expected, AtorAvaliado actual) {}
}
