package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CriterioAvaliacaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriterioAvaliacaoAllPropertiesEquals(CriterioAvaliacao expected, CriterioAvaliacao actual) {
        assertCriterioAvaliacaoAutoGeneratedPropertiesEquals(expected, actual);
        assertCriterioAvaliacaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriterioAvaliacaoAllUpdatablePropertiesEquals(CriterioAvaliacao expected, CriterioAvaliacao actual) {
        assertCriterioAvaliacaoUpdatableFieldsEquals(expected, actual);
        assertCriterioAvaliacaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriterioAvaliacaoAutoGeneratedPropertiesEquals(CriterioAvaliacao expected, CriterioAvaliacao actual) {
        assertThat(expected)
            .as("Verify CriterioAvaliacao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriterioAvaliacaoUpdatableFieldsEquals(CriterioAvaliacao expected, CriterioAvaliacao actual) {
        assertThat(expected)
            .as("Verify CriterioAvaliacao relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCriterioAvaliacaoUpdatableRelationshipsEquals(CriterioAvaliacao expected, CriterioAvaliacao actual) {}
}
