package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DenunciaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDenunciaAllPropertiesEquals(Denuncia expected, Denuncia actual) {
        assertDenunciaAutoGeneratedPropertiesEquals(expected, actual);
        assertDenunciaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDenunciaAllUpdatablePropertiesEquals(Denuncia expected, Denuncia actual) {
        assertDenunciaUpdatableFieldsEquals(expected, actual);
        assertDenunciaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDenunciaAutoGeneratedPropertiesEquals(Denuncia expected, Denuncia actual) {
        assertThat(expected)
            .as("Verify Denuncia auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDenunciaUpdatableFieldsEquals(Denuncia expected, Denuncia actual) {
        assertThat(expected)
            .as("Verify Denuncia relevant properties")
            .satisfies(e -> assertThat(e.getTitulo()).as("check titulo").isEqualTo(actual.getTitulo()))
            .satisfies(e -> assertThat(e.getMensagem()).as("check mensagem").isEqualTo(actual.getMensagem()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDenunciaUpdatableRelationshipsEquals(Denuncia expected, Denuncia actual) {}
}
