package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DepartamentoEmpresaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartamentoEmpresaAllPropertiesEquals(DepartamentoEmpresa expected, DepartamentoEmpresa actual) {
        assertDepartamentoEmpresaAutoGeneratedPropertiesEquals(expected, actual);
        assertDepartamentoEmpresaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartamentoEmpresaAllUpdatablePropertiesEquals(DepartamentoEmpresa expected, DepartamentoEmpresa actual) {
        assertDepartamentoEmpresaUpdatableFieldsEquals(expected, actual);
        assertDepartamentoEmpresaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartamentoEmpresaAutoGeneratedPropertiesEquals(DepartamentoEmpresa expected, DepartamentoEmpresa actual) {
        assertThat(expected)
            .as("Verify DepartamentoEmpresa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartamentoEmpresaUpdatableFieldsEquals(DepartamentoEmpresa expected, DepartamentoEmpresa actual) {
        assertThat(expected)
            .as("Verify DepartamentoEmpresa relevant properties")
            .satisfies(e -> assertThat(e.getPontuacao()).as("check pontuacao").isEqualTo(actual.getPontuacao()))
            .satisfies(e -> assertThat(e.getDepoimento()).as("check depoimento").isEqualTo(actual.getDepoimento()))
            .satisfies(e -> assertThat(e.getReclamacao()).as("check reclamacao").isEqualTo(actual.getReclamacao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDepartamentoEmpresaUpdatableRelationshipsEquals(DepartamentoEmpresa expected, DepartamentoEmpresa actual) {
        assertThat(expected)
            .as("Verify DepartamentoEmpresa relationships")
            .satisfies(e -> assertThat(e.getDepartamento()).as("check departamento").isEqualTo(actual.getDepartamento()))
            .satisfies(e -> assertThat(e.getEmpresa()).as("check empresa").isEqualTo(actual.getEmpresa()))
            .satisfies(e -> assertThat(e.getContador()).as("check contador").isEqualTo(actual.getContador()));
    }
}
