package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DescontoPlanoContabilAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDescontoPlanoContabilAllPropertiesEquals(DescontoPlanoContabil expected, DescontoPlanoContabil actual) {
        assertDescontoPlanoContabilAutoGeneratedPropertiesEquals(expected, actual);
        assertDescontoPlanoContabilAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDescontoPlanoContabilAllUpdatablePropertiesEquals(
        DescontoPlanoContabil expected,
        DescontoPlanoContabil actual
    ) {
        assertDescontoPlanoContabilUpdatableFieldsEquals(expected, actual);
        assertDescontoPlanoContabilUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDescontoPlanoContabilAutoGeneratedPropertiesEquals(
        DescontoPlanoContabil expected,
        DescontoPlanoContabil actual
    ) {
        assertThat(expected)
            .as("Verify DescontoPlanoContabil auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDescontoPlanoContabilUpdatableFieldsEquals(DescontoPlanoContabil expected, DescontoPlanoContabil actual) {
        assertThat(expected)
            .as("Verify DescontoPlanoContabil relevant properties")
            .satisfies(e -> assertThat(e.getPercentual()).as("check percentual").isEqualTo(actual.getPercentual()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDescontoPlanoContabilUpdatableRelationshipsEquals(
        DescontoPlanoContabil expected,
        DescontoPlanoContabil actual
    ) {
        assertThat(expected)
            .as("Verify DescontoPlanoContabil relationships")
            .satisfies(e -> assertThat(e.getPeriodoPagamento()).as("check periodoPagamento").isEqualTo(actual.getPeriodoPagamento()))
            .satisfies(e -> assertThat(e.getPlanoContabil()).as("check planoContabil").isEqualTo(actual.getPlanoContabil()));
    }
}
