package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DescontoPlanoContaAzulAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDescontoPlanoContaAzulAllPropertiesEquals(DescontoPlanoContaAzul expected, DescontoPlanoContaAzul actual) {
        assertDescontoPlanoContaAzulAutoGeneratedPropertiesEquals(expected, actual);
        assertDescontoPlanoContaAzulAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDescontoPlanoContaAzulAllUpdatablePropertiesEquals(
        DescontoPlanoContaAzul expected,
        DescontoPlanoContaAzul actual
    ) {
        assertDescontoPlanoContaAzulUpdatableFieldsEquals(expected, actual);
        assertDescontoPlanoContaAzulUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDescontoPlanoContaAzulAutoGeneratedPropertiesEquals(
        DescontoPlanoContaAzul expected,
        DescontoPlanoContaAzul actual
    ) {
        assertThat(expected)
            .as("Verify DescontoPlanoContaAzul auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDescontoPlanoContaAzulUpdatableFieldsEquals(DescontoPlanoContaAzul expected, DescontoPlanoContaAzul actual) {
        assertThat(expected)
            .as("Verify DescontoPlanoContaAzul relevant properties")
            .satisfies(e -> assertThat(e.getPercentual()).as("check percentual").isEqualTo(actual.getPercentual()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDescontoPlanoContaAzulUpdatableRelationshipsEquals(
        DescontoPlanoContaAzul expected,
        DescontoPlanoContaAzul actual
    ) {
        assertThat(expected)
            .as("Verify DescontoPlanoContaAzul relationships")
            .satisfies(e -> assertThat(e.getPlanoContaAzul()).as("check planoContaAzul").isEqualTo(actual.getPlanoContaAzul()))
            .satisfies(e -> assertThat(e.getPeriodoPagamento()).as("check periodoPagamento").isEqualTo(actual.getPeriodoPagamento()));
    }
}
