package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DivisaoCnaeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDivisaoCnaeAllPropertiesEquals(DivisaoCnae expected, DivisaoCnae actual) {
        assertDivisaoCnaeAutoGeneratedPropertiesEquals(expected, actual);
        assertDivisaoCnaeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDivisaoCnaeAllUpdatablePropertiesEquals(DivisaoCnae expected, DivisaoCnae actual) {
        assertDivisaoCnaeUpdatableFieldsEquals(expected, actual);
        assertDivisaoCnaeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDivisaoCnaeAutoGeneratedPropertiesEquals(DivisaoCnae expected, DivisaoCnae actual) {
        assertThat(expected)
            .as("Verify DivisaoCnae auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDivisaoCnaeUpdatableFieldsEquals(DivisaoCnae expected, DivisaoCnae actual) {
        assertThat(expected)
            .as("Verify DivisaoCnae relevant properties")
            .satisfies(e -> assertThat(e.getCodigo()).as("check codigo").isEqualTo(actual.getCodigo()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDivisaoCnaeUpdatableRelationshipsEquals(DivisaoCnae expected, DivisaoCnae actual) {
        assertThat(expected)
            .as("Verify DivisaoCnae relationships")
            .satisfies(e -> assertThat(e.getSecao()).as("check secao").isEqualTo(actual.getSecao()));
    }
}
