package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EnderecoEmpresaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoEmpresaAllPropertiesEquals(EnderecoEmpresa expected, EnderecoEmpresa actual) {
        assertEnderecoEmpresaAutoGeneratedPropertiesEquals(expected, actual);
        assertEnderecoEmpresaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoEmpresaAllUpdatablePropertiesEquals(EnderecoEmpresa expected, EnderecoEmpresa actual) {
        assertEnderecoEmpresaUpdatableFieldsEquals(expected, actual);
        assertEnderecoEmpresaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoEmpresaAutoGeneratedPropertiesEquals(EnderecoEmpresa expected, EnderecoEmpresa actual) {
        assertThat(expected)
            .as("Verify EnderecoEmpresa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoEmpresaUpdatableFieldsEquals(EnderecoEmpresa expected, EnderecoEmpresa actual) {
        assertThat(expected)
            .as("Verify EnderecoEmpresa relevant properties")
            .satisfies(e -> assertThat(e.getLogradouro()).as("check logradouro").isEqualTo(actual.getLogradouro()))
            .satisfies(e -> assertThat(e.getNumero()).as("check numero").isEqualTo(actual.getNumero()))
            .satisfies(e -> assertThat(e.getComplemento()).as("check complemento").isEqualTo(actual.getComplemento()))
            .satisfies(e -> assertThat(e.getBairro()).as("check bairro").isEqualTo(actual.getBairro()))
            .satisfies(e -> assertThat(e.getCep()).as("check cep").isEqualTo(actual.getCep()))
            .satisfies(e -> assertThat(e.getPrincipal()).as("check principal").isEqualTo(actual.getPrincipal()))
            .satisfies(e -> assertThat(e.getFilial()).as("check filial").isEqualTo(actual.getFilial()))
            .satisfies(e -> assertThat(e.getEnderecoFiscal()).as("check enderecoFiscal").isEqualTo(actual.getEnderecoFiscal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEnderecoEmpresaUpdatableRelationshipsEquals(EnderecoEmpresa expected, EnderecoEmpresa actual) {
        assertThat(expected)
            .as("Verify EnderecoEmpresa relationships")
            .satisfies(e -> assertThat(e.getEmpresa()).as("check empresa").isEqualTo(actual.getEmpresa()))
            .satisfies(e -> assertThat(e.getCidade()).as("check cidade").isEqualTo(actual.getCidade()));
    }
}
