package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EsferaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEsferaAllPropertiesEquals(Esfera expected, Esfera actual) {
        assertEsferaAutoGeneratedPropertiesEquals(expected, actual);
        assertEsferaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEsferaAllUpdatablePropertiesEquals(Esfera expected, Esfera actual) {
        assertEsferaUpdatableFieldsEquals(expected, actual);
        assertEsferaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEsferaAutoGeneratedPropertiesEquals(Esfera expected, Esfera actual) {
        assertThat(expected)
            .as("Verify Esfera auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEsferaUpdatableFieldsEquals(Esfera expected, Esfera actual) {
        assertThat(expected)
            .as("Verify Esfera relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEsferaUpdatableRelationshipsEquals(Esfera expected, Esfera actual) {}
}
