package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EstadoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoAllPropertiesEquals(Estado expected, Estado actual) {
        assertEstadoAutoGeneratedPropertiesEquals(expected, actual);
        assertEstadoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoAllUpdatablePropertiesEquals(Estado expected, Estado actual) {
        assertEstadoUpdatableFieldsEquals(expected, actual);
        assertEstadoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoAutoGeneratedPropertiesEquals(Estado expected, Estado actual) {
        assertThat(expected)
            .as("Verify Estado auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoUpdatableFieldsEquals(Estado expected, Estado actual) {
        assertThat(expected)
            .as("Verify Estado relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getNaturalidade()).as("check naturalidade").isEqualTo(actual.getNaturalidade()))
            .satisfies(e -> assertThat(e.getSigla()).as("check sigla").isEqualTo(actual.getSigla()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEstadoUpdatableRelationshipsEquals(Estado expected, Estado actual) {}
}
