package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EtapaFluxoModeloAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtapaFluxoModeloAllPropertiesEquals(EtapaFluxoModelo expected, EtapaFluxoModelo actual) {
        assertEtapaFluxoModeloAutoGeneratedPropertiesEquals(expected, actual);
        assertEtapaFluxoModeloAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtapaFluxoModeloAllUpdatablePropertiesEquals(EtapaFluxoModelo expected, EtapaFluxoModelo actual) {
        assertEtapaFluxoModeloUpdatableFieldsEquals(expected, actual);
        assertEtapaFluxoModeloUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtapaFluxoModeloAutoGeneratedPropertiesEquals(EtapaFluxoModelo expected, EtapaFluxoModelo actual) {
        assertThat(expected)
            .as("Verify EtapaFluxoModelo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtapaFluxoModeloUpdatableFieldsEquals(EtapaFluxoModelo expected, EtapaFluxoModelo actual) {
        assertThat(expected)
            .as("Verify EtapaFluxoModelo relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getOrdem()).as("check ordem").isEqualTo(actual.getOrdem()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEtapaFluxoModeloUpdatableRelationshipsEquals(EtapaFluxoModelo expected, EtapaFluxoModelo actual) {
        assertThat(expected)
            .as("Verify EtapaFluxoModelo relationships")
            .satisfies(e -> assertThat(e.getFluxoModelo()).as("check fluxoModelo").isEqualTo(actual.getFluxoModelo()));
    }
}
