package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FeedBackContadorParaUsuarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedBackContadorParaUsuarioAllPropertiesEquals(
        FeedBackContadorParaUsuario expected,
        FeedBackContadorParaUsuario actual
    ) {
        assertFeedBackContadorParaUsuarioAutoGeneratedPropertiesEquals(expected, actual);
        assertFeedBackContadorParaUsuarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedBackContadorParaUsuarioAllUpdatablePropertiesEquals(
        FeedBackContadorParaUsuario expected,
        FeedBackContadorParaUsuario actual
    ) {
        assertFeedBackContadorParaUsuarioUpdatableFieldsEquals(expected, actual);
        assertFeedBackContadorParaUsuarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedBackContadorParaUsuarioAutoGeneratedPropertiesEquals(
        FeedBackContadorParaUsuario expected,
        FeedBackContadorParaUsuario actual
    ) {
        assertThat(expected)
            .as("Verify FeedBackContadorParaUsuario auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedBackContadorParaUsuarioUpdatableFieldsEquals(
        FeedBackContadorParaUsuario expected,
        FeedBackContadorParaUsuario actual
    ) {
        assertThat(expected)
            .as("Verify FeedBackContadorParaUsuario relevant properties")
            .satisfies(e -> assertThat(e.getComentario()).as("check comentario").isEqualTo(actual.getComentario()))
            .satisfies(e -> assertThat(e.getPontuacao()).as("check pontuacao").isEqualTo(actual.getPontuacao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFeedBackContadorParaUsuarioUpdatableRelationshipsEquals(
        FeedBackContadorParaUsuario expected,
        FeedBackContadorParaUsuario actual
    ) {
        assertThat(expected)
            .as("Verify FeedBackContadorParaUsuario relationships")
            .satisfies(
                e -> assertThat(e.getCriterioAvaliacaoAtor()).as("check criterioAvaliacaoAtor").isEqualTo(actual.getCriterioAvaliacaoAtor())
            )
            .satisfies(e -> assertThat(e.getUsuarioEmpresa()).as("check usuarioEmpresa").isEqualTo(actual.getUsuarioEmpresa()))
            .satisfies(e -> assertThat(e.getContador()).as("check contador").isEqualTo(actual.getContador()))
            .satisfies(e -> assertThat(e.getOrdemServico()).as("check ordemServico").isEqualTo(actual.getOrdemServico()));
    }
}
