package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FluxoModeloAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFluxoModeloAllPropertiesEquals(FluxoModelo expected, FluxoModelo actual) {
        assertFluxoModeloAutoGeneratedPropertiesEquals(expected, actual);
        assertFluxoModeloAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFluxoModeloAllUpdatablePropertiesEquals(FluxoModelo expected, FluxoModelo actual) {
        assertFluxoModeloUpdatableFieldsEquals(expected, actual);
        assertFluxoModeloUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFluxoModeloAutoGeneratedPropertiesEquals(FluxoModelo expected, FluxoModelo actual) {
        assertThat(expected)
            .as("Verify FluxoModelo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFluxoModeloUpdatableFieldsEquals(FluxoModelo expected, FluxoModelo actual) {
        assertThat(expected)
            .as("Verify FluxoModelo relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFluxoModeloUpdatableRelationshipsEquals(FluxoModelo expected, FluxoModelo actual) {
        assertThat(expected)
            .as("Verify FluxoModelo relationships")
            .satisfies(e -> assertThat(e.getCidade()).as("check cidade").isEqualTo(actual.getCidade()));
    }
}
