package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FluxoExecucaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFluxoExecucaoAllPropertiesEquals(FluxoExecucao expected, FluxoExecucao actual) {
        assertFluxoExecucaoAutoGeneratedPropertiesEquals(expected, actual);
        assertFluxoExecucaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFluxoExecucaoAllUpdatablePropertiesEquals(FluxoExecucao expected, FluxoExecucao actual) {
        assertFluxoExecucaoUpdatableFieldsEquals(expected, actual);
        assertFluxoExecucaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFluxoExecucaoAutoGeneratedPropertiesEquals(FluxoExecucao expected, FluxoExecucao actual) {
        assertThat(expected)
            .as("Verify FluxoExecucao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFluxoExecucaoUpdatableFieldsEquals(FluxoExecucao expected, FluxoExecucao actual) {
        assertThat(expected)
            .as("Verify FluxoExecucao relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFluxoExecucaoUpdatableRelationshipsEquals(FluxoExecucao expected, FluxoExecucao actual) {}
}
