package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FormaDePagamentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormaDePagamentoAllPropertiesEquals(FormaDePagamento expected, FormaDePagamento actual) {
        assertFormaDePagamentoAutoGeneratedPropertiesEquals(expected, actual);
        assertFormaDePagamentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormaDePagamentoAllUpdatablePropertiesEquals(FormaDePagamento expected, FormaDePagamento actual) {
        assertFormaDePagamentoUpdatableFieldsEquals(expected, actual);
        assertFormaDePagamentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormaDePagamentoAutoGeneratedPropertiesEquals(FormaDePagamento expected, FormaDePagamento actual) {
        assertThat(expected)
            .as("Verify FormaDePagamento auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormaDePagamentoUpdatableFieldsEquals(FormaDePagamento expected, FormaDePagamento actual) {
        assertThat(expected)
            .as("Verify FormaDePagamento relevant properties")
            .satisfies(e -> assertThat(e.getForma()).as("check forma").isEqualTo(actual.getForma()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getDisponivel()).as("check disponivel").isEqualTo(actual.getDisponivel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFormaDePagamentoUpdatableRelationshipsEquals(FormaDePagamento expected, FormaDePagamento actual) {}
}
