package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FrequenciaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrequenciaAllPropertiesEquals(Frequencia expected, Frequencia actual) {
        assertFrequenciaAutoGeneratedPropertiesEquals(expected, actual);
        assertFrequenciaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrequenciaAllUpdatablePropertiesEquals(Frequencia expected, Frequencia actual) {
        assertFrequenciaUpdatableFieldsEquals(expected, actual);
        assertFrequenciaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrequenciaAutoGeneratedPropertiesEquals(Frequencia expected, Frequencia actual) {
        assertThat(expected)
            .as("Verify Frequencia auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrequenciaUpdatableFieldsEquals(Frequencia expected, Frequencia actual) {
        assertThat(expected)
            .as("Verify Frequencia relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getNumeroDias()).as("check numeroDias").isEqualTo(actual.getNumeroDias()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFrequenciaUpdatableRelationshipsEquals(Frequencia expected, Frequencia actual) {}
}
