package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GatewayPagamentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGatewayPagamentoAllPropertiesEquals(GatewayPagamento expected, GatewayPagamento actual) {
        assertGatewayPagamentoAutoGeneratedPropertiesEquals(expected, actual);
        assertGatewayPagamentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGatewayPagamentoAllUpdatablePropertiesEquals(GatewayPagamento expected, GatewayPagamento actual) {
        assertGatewayPagamentoUpdatableFieldsEquals(expected, actual);
        assertGatewayPagamentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGatewayPagamentoAutoGeneratedPropertiesEquals(GatewayPagamento expected, GatewayPagamento actual) {
        assertThat(expected)
            .as("Verify GatewayPagamento auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGatewayPagamentoUpdatableFieldsEquals(GatewayPagamento expected, GatewayPagamento actual) {
        assertThat(expected)
            .as("Verify GatewayPagamento relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGatewayPagamentoUpdatableRelationshipsEquals(GatewayPagamento expected, GatewayPagamento actual) {}
}
