package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GrupoAcessoEmpresaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAcessoEmpresaAllPropertiesEquals(GrupoAcessoEmpresa expected, GrupoAcessoEmpresa actual) {
        assertGrupoAcessoEmpresaAutoGeneratedPropertiesEquals(expected, actual);
        assertGrupoAcessoEmpresaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAcessoEmpresaAllUpdatablePropertiesEquals(GrupoAcessoEmpresa expected, GrupoAcessoEmpresa actual) {
        assertGrupoAcessoEmpresaUpdatableFieldsEquals(expected, actual);
        assertGrupoAcessoEmpresaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAcessoEmpresaAutoGeneratedPropertiesEquals(GrupoAcessoEmpresa expected, GrupoAcessoEmpresa actual) {
        assertThat(expected)
            .as("Verify GrupoAcessoEmpresa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAcessoEmpresaUpdatableFieldsEquals(GrupoAcessoEmpresa expected, GrupoAcessoEmpresa actual) {
        assertThat(expected)
            .as("Verify GrupoAcessoEmpresa relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAcessoEmpresaUpdatableRelationshipsEquals(GrupoAcessoEmpresa expected, GrupoAcessoEmpresa actual) {
        assertThat(expected)
            .as("Verify GrupoAcessoEmpresa relationships")
            .satisfies(e -> assertThat(e.getAssinaturaEmpresa()).as("check assinaturaEmpresa").isEqualTo(actual.getAssinaturaEmpresa()));
    }
}
