package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GrupoAcessoPadraoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAcessoPadraoAllPropertiesEquals(GrupoAcessoPadrao expected, GrupoAcessoPadrao actual) {
        assertGrupoAcessoPadraoAutoGeneratedPropertiesEquals(expected, actual);
        assertGrupoAcessoPadraoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAcessoPadraoAllUpdatablePropertiesEquals(GrupoAcessoPadrao expected, GrupoAcessoPadrao actual) {
        assertGrupoAcessoPadraoUpdatableFieldsEquals(expected, actual);
        assertGrupoAcessoPadraoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAcessoPadraoAutoGeneratedPropertiesEquals(GrupoAcessoPadrao expected, GrupoAcessoPadrao actual) {
        assertThat(expected)
            .as("Verify GrupoAcessoPadrao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAcessoPadraoUpdatableFieldsEquals(GrupoAcessoPadrao expected, GrupoAcessoPadrao actual) {
        assertThat(expected)
            .as("Verify GrupoAcessoPadrao relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoAcessoPadraoUpdatableRelationshipsEquals(GrupoAcessoPadrao expected, GrupoAcessoPadrao actual) {}
}
