package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GrupoCnaeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoCnaeAllPropertiesEquals(GrupoCnae expected, GrupoCnae actual) {
        assertGrupoCnaeAutoGeneratedPropertiesEquals(expected, actual);
        assertGrupoCnaeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoCnaeAllUpdatablePropertiesEquals(GrupoCnae expected, GrupoCnae actual) {
        assertGrupoCnaeUpdatableFieldsEquals(expected, actual);
        assertGrupoCnaeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoCnaeAutoGeneratedPropertiesEquals(GrupoCnae expected, GrupoCnae actual) {
        assertThat(expected)
            .as("Verify GrupoCnae auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoCnaeUpdatableFieldsEquals(GrupoCnae expected, GrupoCnae actual) {
        assertThat(expected)
            .as("Verify GrupoCnae relevant properties")
            .satisfies(e -> assertThat(e.getCodigo()).as("check codigo").isEqualTo(actual.getCodigo()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGrupoCnaeUpdatableRelationshipsEquals(GrupoCnae expected, GrupoCnae actual) {
        assertThat(expected)
            .as("Verify GrupoCnae relationships")
            .satisfies(e -> assertThat(e.getDivisao()).as("check divisao").isEqualTo(actual.getDivisao()));
    }
}
