package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ImpostoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImpostoAllPropertiesEquals(Imposto expected, Imposto actual) {
        assertImpostoAutoGeneratedPropertiesEquals(expected, actual);
        assertImpostoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImpostoAllUpdatablePropertiesEquals(Imposto expected, Imposto actual) {
        assertImpostoUpdatableFieldsEquals(expected, actual);
        assertImpostoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImpostoAutoGeneratedPropertiesEquals(Imposto expected, Imposto actual) {
        assertThat(expected)
            .as("Verify Imposto auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImpostoUpdatableFieldsEquals(Imposto expected, Imposto actual) {
        assertThat(expected)
            .as("Verify Imposto relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getSigla()).as("check sigla").isEqualTo(actual.getSigla()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertImpostoUpdatableRelationshipsEquals(Imposto expected, Imposto actual) {
        assertThat(expected)
            .as("Verify Imposto relationships")
            .satisfies(e -> assertThat(e.getEsfera()).as("check esfera").isEqualTo(actual.getEsfera()));
    }
}
