package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ModuloAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuloAllPropertiesEquals(Modulo expected, Modulo actual) {
        assertModuloAutoGeneratedPropertiesEquals(expected, actual);
        assertModuloAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuloAllUpdatablePropertiesEquals(Modulo expected, Modulo actual) {
        assertModuloUpdatableFieldsEquals(expected, actual);
        assertModuloUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuloAutoGeneratedPropertiesEquals(Modulo expected, Modulo actual) {
        assertThat(expected)
            .as("Verify Modulo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuloUpdatableFieldsEquals(Modulo expected, Modulo actual) {
        assertThat(expected)
            .as("Verify Modulo relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertModuloUpdatableRelationshipsEquals(Modulo expected, Modulo actual) {
        assertThat(expected)
            .as("Verify Modulo relationships")
            .satisfies(e -> assertThat(e.getSistema()).as("check sistema").isEqualTo(actual.getSistema()));
    }
}
