package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PerfilAcessoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilAcessoAllPropertiesEquals(PerfilAcesso expected, PerfilAcesso actual) {
        assertPerfilAcessoAutoGeneratedPropertiesEquals(expected, actual);
        assertPerfilAcessoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilAcessoAllUpdatablePropertiesEquals(PerfilAcesso expected, PerfilAcesso actual) {
        assertPerfilAcessoUpdatableFieldsEquals(expected, actual);
        assertPerfilAcessoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilAcessoAutoGeneratedPropertiesEquals(PerfilAcesso expected, PerfilAcesso actual) {
        assertThat(expected)
            .as("Verify PerfilAcesso auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilAcessoUpdatableFieldsEquals(PerfilAcesso expected, PerfilAcesso actual) {
        assertThat(expected)
            .as("Verify PerfilAcesso relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilAcessoUpdatableRelationshipsEquals(PerfilAcesso expected, PerfilAcesso actual) {}
}
