package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PerfilRedeSocialAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilRedeSocialAllPropertiesEquals(PerfilRedeSocial expected, PerfilRedeSocial actual) {
        assertPerfilRedeSocialAutoGeneratedPropertiesEquals(expected, actual);
        assertPerfilRedeSocialAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilRedeSocialAllUpdatablePropertiesEquals(PerfilRedeSocial expected, PerfilRedeSocial actual) {
        assertPerfilRedeSocialUpdatableFieldsEquals(expected, actual);
        assertPerfilRedeSocialUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilRedeSocialAutoGeneratedPropertiesEquals(PerfilRedeSocial expected, PerfilRedeSocial actual) {
        assertThat(expected)
            .as("Verify PerfilRedeSocial auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilRedeSocialUpdatableFieldsEquals(PerfilRedeSocial expected, PerfilRedeSocial actual) {
        assertThat(expected)
            .as("Verify PerfilRedeSocial relevant properties")
            .satisfies(e -> assertThat(e.getRede()).as("check rede").isEqualTo(actual.getRede()))
            .satisfies(e -> assertThat(e.getUrlPerfil()).as("check urlPerfil").isEqualTo(actual.getUrlPerfil()))
            .satisfies(e -> assertThat(e.getTipoRede()).as("check tipoRede").isEqualTo(actual.getTipoRede()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilRedeSocialUpdatableRelationshipsEquals(PerfilRedeSocial expected, PerfilRedeSocial actual) {}
}
