package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PerfilContadorDepartamentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilContadorDepartamentoAllPropertiesEquals(
        PerfilContadorDepartamento expected,
        PerfilContadorDepartamento actual
    ) {
        assertPerfilContadorDepartamentoAutoGeneratedPropertiesEquals(expected, actual);
        assertPerfilContadorDepartamentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilContadorDepartamentoAllUpdatablePropertiesEquals(
        PerfilContadorDepartamento expected,
        PerfilContadorDepartamento actual
    ) {
        assertPerfilContadorDepartamentoUpdatableFieldsEquals(expected, actual);
        assertPerfilContadorDepartamentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilContadorDepartamentoAutoGeneratedPropertiesEquals(
        PerfilContadorDepartamento expected,
        PerfilContadorDepartamento actual
    ) {
        assertThat(expected)
            .as("Verify PerfilContadorDepartamento auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilContadorDepartamentoUpdatableFieldsEquals(
        PerfilContadorDepartamento expected,
        PerfilContadorDepartamento actual
    ) {
        assertThat(expected)
            .as("Verify PerfilContadorDepartamento relevant properties")
            .satisfies(e -> assertThat(e.getQuantidadeEmpresas()).as("check quantidadeEmpresas").isEqualTo(actual.getQuantidadeEmpresas()))
            .satisfies(
                e -> assertThat(e.getPercentualExperiencia()).as("check percentualExperiencia").isEqualTo(actual.getPercentualExperiencia())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPerfilContadorDepartamentoUpdatableRelationshipsEquals(
        PerfilContadorDepartamento expected,
        PerfilContadorDepartamento actual
    ) {
        assertThat(expected)
            .as("Verify PerfilContadorDepartamento relationships")
            .satisfies(e -> assertThat(e.getDepartamento()).as("check departamento").isEqualTo(actual.getDepartamento()))
            .satisfies(e -> assertThat(e.getPerfilContador()).as("check perfilContador").isEqualTo(actual.getPerfilContador()));
    }
}
