package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PeriodoPagamentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodoPagamentoAllPropertiesEquals(PeriodoPagamento expected, PeriodoPagamento actual) {
        assertPeriodoPagamentoAutoGeneratedPropertiesEquals(expected, actual);
        assertPeriodoPagamentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodoPagamentoAllUpdatablePropertiesEquals(PeriodoPagamento expected, PeriodoPagamento actual) {
        assertPeriodoPagamentoUpdatableFieldsEquals(expected, actual);
        assertPeriodoPagamentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodoPagamentoAutoGeneratedPropertiesEquals(PeriodoPagamento expected, PeriodoPagamento actual) {
        assertThat(expected)
            .as("Verify PeriodoPagamento auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodoPagamentoUpdatableFieldsEquals(PeriodoPagamento expected, PeriodoPagamento actual) {
        assertThat(expected)
            .as("Verify PeriodoPagamento relevant properties")
            .satisfies(e -> assertThat(e.getPeriodo()).as("check periodo").isEqualTo(actual.getPeriodo()))
            .satisfies(e -> assertThat(e.getNumeroDias()).as("check numeroDias").isEqualTo(actual.getNumeroDias()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPeriodoPagamentoUpdatableRelationshipsEquals(PeriodoPagamento expected, PeriodoPagamento actual) {}
}
