package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PermisaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermisaoAllPropertiesEquals(Permisao expected, Permisao actual) {
        assertPermisaoAutoGeneratedPropertiesEquals(expected, actual);
        assertPermisaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermisaoAllUpdatablePropertiesEquals(Permisao expected, Permisao actual) {
        assertPermisaoUpdatableFieldsEquals(expected, actual);
        assertPermisaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermisaoAutoGeneratedPropertiesEquals(Permisao expected, Permisao actual) {
        assertThat(expected)
            .as("Verify Permisao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermisaoUpdatableFieldsEquals(Permisao expected, Permisao actual) {
        assertThat(expected)
            .as("Verify Permisao relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getLabel()).as("check label").isEqualTo(actual.getLabel()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPermisaoUpdatableRelationshipsEquals(Permisao expected, Permisao actual) {}
}
