package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PessoajuridicaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoajuridicaAllPropertiesEquals(Pessoajuridica expected, Pessoajuridica actual) {
        assertPessoajuridicaAutoGeneratedPropertiesEquals(expected, actual);
        assertPessoajuridicaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoajuridicaAllUpdatablePropertiesEquals(Pessoajuridica expected, Pessoajuridica actual) {
        assertPessoajuridicaUpdatableFieldsEquals(expected, actual);
        assertPessoajuridicaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoajuridicaAutoGeneratedPropertiesEquals(Pessoajuridica expected, Pessoajuridica actual) {
        assertThat(expected)
            .as("Verify Pessoajuridica auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoajuridicaUpdatableFieldsEquals(Pessoajuridica expected, Pessoajuridica actual) {
        assertThat(expected)
            .as("Verify Pessoajuridica relevant properties")
            .satisfies(e -> assertThat(e.getRazaoSocial()).as("check razaoSocial").isEqualTo(actual.getRazaoSocial()))
            .satisfies(e -> assertThat(e.getNomeFantasia()).as("check nomeFantasia").isEqualTo(actual.getNomeFantasia()))
            .satisfies(e -> assertThat(e.getCnpj()).as("check cnpj").isEqualTo(actual.getCnpj()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPessoajuridicaUpdatableRelationshipsEquals(Pessoajuridica expected, Pessoajuridica actual) {}
}
