package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PrazoAssinaturaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrazoAssinaturaAllPropertiesEquals(PrazoAssinatura expected, PrazoAssinatura actual) {
        assertPrazoAssinaturaAutoGeneratedPropertiesEquals(expected, actual);
        assertPrazoAssinaturaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrazoAssinaturaAllUpdatablePropertiesEquals(PrazoAssinatura expected, PrazoAssinatura actual) {
        assertPrazoAssinaturaUpdatableFieldsEquals(expected, actual);
        assertPrazoAssinaturaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrazoAssinaturaAutoGeneratedPropertiesEquals(PrazoAssinatura expected, PrazoAssinatura actual) {
        assertThat(expected)
            .as("Verify PrazoAssinatura auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrazoAssinaturaUpdatableFieldsEquals(PrazoAssinatura expected, PrazoAssinatura actual) {
        assertThat(expected)
            .as("Verify PrazoAssinatura relevant properties")
            .satisfies(e -> assertThat(e.getPrazo()).as("check prazo").isEqualTo(actual.getPrazo()))
            .satisfies(e -> assertThat(e.getMeses()).as("check meses").isEqualTo(actual.getMeses()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPrazoAssinaturaUpdatableRelationshipsEquals(PrazoAssinatura expected, PrazoAssinatura actual) {}
}
