package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RamoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRamoAllPropertiesEquals(Ramo expected, Ramo actual) {
        assertRamoAutoGeneratedPropertiesEquals(expected, actual);
        assertRamoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRamoAllUpdatablePropertiesEquals(Ramo expected, Ramo actual) {
        assertRamoUpdatableFieldsEquals(expected, actual);
        assertRamoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRamoAutoGeneratedPropertiesEquals(Ramo expected, Ramo actual) {
        assertThat(expected)
            .as("Verify Ramo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRamoUpdatableFieldsEquals(Ramo expected, Ramo actual) {
        assertThat(expected)
            .as("Verify Ramo relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRamoUpdatableRelationshipsEquals(Ramo expected, Ramo actual) {}
}
