package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RedeSocialEmpresaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedeSocialEmpresaAllPropertiesEquals(RedeSocialEmpresa expected, RedeSocialEmpresa actual) {
        assertRedeSocialEmpresaAutoGeneratedPropertiesEquals(expected, actual);
        assertRedeSocialEmpresaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedeSocialEmpresaAllUpdatablePropertiesEquals(RedeSocialEmpresa expected, RedeSocialEmpresa actual) {
        assertRedeSocialEmpresaUpdatableFieldsEquals(expected, actual);
        assertRedeSocialEmpresaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedeSocialEmpresaAutoGeneratedPropertiesEquals(RedeSocialEmpresa expected, RedeSocialEmpresa actual) {
        assertThat(expected)
            .as("Verify RedeSocialEmpresa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedeSocialEmpresaUpdatableFieldsEquals(RedeSocialEmpresa expected, RedeSocialEmpresa actual) {
        assertThat(expected)
            .as("Verify RedeSocialEmpresa relevant properties")
            .satisfies(e -> assertThat(e.getPerfil()).as("check perfil").isEqualTo(actual.getPerfil()))
            .satisfies(e -> assertThat(e.getUrlPerfil()).as("check urlPerfil").isEqualTo(actual.getUrlPerfil()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRedeSocialEmpresaUpdatableRelationshipsEquals(RedeSocialEmpresa expected, RedeSocialEmpresa actual) {
        assertThat(expected)
            .as("Verify RedeSocialEmpresa relationships")
            .satisfies(e -> assertThat(e.getRedeSocial()).as("check redeSocial").isEqualTo(actual.getRedeSocial()))
            .satisfies(e -> assertThat(e.getPessoajuridica()).as("check pessoajuridica").isEqualTo(actual.getPessoajuridica()));
    }
}
