package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SecaoCnaeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecaoCnaeAllPropertiesEquals(SecaoCnae expected, SecaoCnae actual) {
        assertSecaoCnaeAutoGeneratedPropertiesEquals(expected, actual);
        assertSecaoCnaeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecaoCnaeAllUpdatablePropertiesEquals(SecaoCnae expected, SecaoCnae actual) {
        assertSecaoCnaeUpdatableFieldsEquals(expected, actual);
        assertSecaoCnaeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecaoCnaeAutoGeneratedPropertiesEquals(SecaoCnae expected, SecaoCnae actual) {
        assertThat(expected)
            .as("Verify SecaoCnae auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecaoCnaeUpdatableFieldsEquals(SecaoCnae expected, SecaoCnae actual) {
        assertThat(expected)
            .as("Verify SecaoCnae relevant properties")
            .satisfies(e -> assertThat(e.getCodigo()).as("check codigo").isEqualTo(actual.getCodigo()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSecaoCnaeUpdatableRelationshipsEquals(SecaoCnae expected, SecaoCnae actual) {}
}
