package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServicoContabilEtapaFluxoModeloAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEtapaFluxoModeloAllPropertiesEquals(
        ServicoContabilEtapaFluxoModelo expected,
        ServicoContabilEtapaFluxoModelo actual
    ) {
        assertServicoContabilEtapaFluxoModeloAutoGeneratedPropertiesEquals(expected, actual);
        assertServicoContabilEtapaFluxoModeloAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEtapaFluxoModeloAllUpdatablePropertiesEquals(
        ServicoContabilEtapaFluxoModelo expected,
        ServicoContabilEtapaFluxoModelo actual
    ) {
        assertServicoContabilEtapaFluxoModeloUpdatableFieldsEquals(expected, actual);
        assertServicoContabilEtapaFluxoModeloUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEtapaFluxoModeloAutoGeneratedPropertiesEquals(
        ServicoContabilEtapaFluxoModelo expected,
        ServicoContabilEtapaFluxoModelo actual
    ) {
        assertThat(expected)
            .as("Verify ServicoContabilEtapaFluxoModelo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEtapaFluxoModeloUpdatableFieldsEquals(
        ServicoContabilEtapaFluxoModelo expected,
        ServicoContabilEtapaFluxoModelo actual
    ) {
        assertThat(expected)
            .as("Verify ServicoContabilEtapaFluxoModelo relevant properties")
            .satisfies(e -> assertThat(e.getOrdem()).as("check ordem").isEqualTo(actual.getOrdem()))
            .satisfies(e -> assertThat(e.getPrazo()).as("check prazo").isEqualTo(actual.getPrazo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEtapaFluxoModeloUpdatableRelationshipsEquals(
        ServicoContabilEtapaFluxoModelo expected,
        ServicoContabilEtapaFluxoModelo actual
    ) {
        assertThat(expected)
            .as("Verify ServicoContabilEtapaFluxoModelo relationships")
            .satisfies(e -> assertThat(e.getEtapaFluxoModelo()).as("check etapaFluxoModelo").isEqualTo(actual.getEtapaFluxoModelo()))
            .satisfies(e -> assertThat(e.getServicoContabil()).as("check servicoContabil").isEqualTo(actual.getServicoContabil()));
    }
}
