package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServicoContabilEtapaFluxoExecucaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEtapaFluxoExecucaoAllPropertiesEquals(
        ServicoContabilEtapaFluxoExecucao expected,
        ServicoContabilEtapaFluxoExecucao actual
    ) {
        assertServicoContabilEtapaFluxoExecucaoAutoGeneratedPropertiesEquals(expected, actual);
        assertServicoContabilEtapaFluxoExecucaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEtapaFluxoExecucaoAllUpdatablePropertiesEquals(
        ServicoContabilEtapaFluxoExecucao expected,
        ServicoContabilEtapaFluxoExecucao actual
    ) {
        assertServicoContabilEtapaFluxoExecucaoUpdatableFieldsEquals(expected, actual);
        assertServicoContabilEtapaFluxoExecucaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEtapaFluxoExecucaoAutoGeneratedPropertiesEquals(
        ServicoContabilEtapaFluxoExecucao expected,
        ServicoContabilEtapaFluxoExecucao actual
    ) {
        assertThat(expected)
            .as("Verify ServicoContabilEtapaFluxoExecucao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEtapaFluxoExecucaoUpdatableFieldsEquals(
        ServicoContabilEtapaFluxoExecucao expected,
        ServicoContabilEtapaFluxoExecucao actual
    ) {
        assertThat(expected)
            .as("Verify ServicoContabilEtapaFluxoExecucao relevant properties")
            .satisfies(e -> assertThat(e.getOrdem()).as("check ordem").isEqualTo(actual.getOrdem()))
            .satisfies(e -> assertThat(e.getFeito()).as("check feito").isEqualTo(actual.getFeito()))
            .satisfies(e -> assertThat(e.getPrazo()).as("check prazo").isEqualTo(actual.getPrazo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEtapaFluxoExecucaoUpdatableRelationshipsEquals(
        ServicoContabilEtapaFluxoExecucao expected,
        ServicoContabilEtapaFluxoExecucao actual
    ) {
        assertThat(expected)
            .as("Verify ServicoContabilEtapaFluxoExecucao relationships")
            .satisfies(e -> assertThat(e.getServicoContabil()).as("check servicoContabil").isEqualTo(actual.getServicoContabil()))
            .satisfies(e -> assertThat(e.getEtapaFluxoExecucao()).as("check etapaFluxoExecucao").isEqualTo(actual.getEtapaFluxoExecucao()));
    }
}
