package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServicoContabilOrdemServicoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilOrdemServicoAllPropertiesEquals(
        ServicoContabilOrdemServico expected,
        ServicoContabilOrdemServico actual
    ) {
        assertServicoContabilOrdemServicoAutoGeneratedPropertiesEquals(expected, actual);
        assertServicoContabilOrdemServicoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilOrdemServicoAllUpdatablePropertiesEquals(
        ServicoContabilOrdemServico expected,
        ServicoContabilOrdemServico actual
    ) {
        assertServicoContabilOrdemServicoUpdatableFieldsEquals(expected, actual);
        assertServicoContabilOrdemServicoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilOrdemServicoAutoGeneratedPropertiesEquals(
        ServicoContabilOrdemServico expected,
        ServicoContabilOrdemServico actual
    ) {
        assertThat(expected)
            .as("Verify ServicoContabilOrdemServico auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilOrdemServicoUpdatableFieldsEquals(
        ServicoContabilOrdemServico expected,
        ServicoContabilOrdemServico actual
    ) {
        assertThat(expected)
            .as("Verify ServicoContabilOrdemServico relevant properties")
            .satisfies(e -> assertThat(e.getDataAdmin()).as("check dataAdmin").isEqualTo(actual.getDataAdmin()))
            .satisfies(e -> assertThat(e.getDataLegal()).as("check dataLegal").isEqualTo(actual.getDataLegal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilOrdemServicoUpdatableRelationshipsEquals(
        ServicoContabilOrdemServico expected,
        ServicoContabilOrdemServico actual
    ) {
        assertThat(expected)
            .as("Verify ServicoContabilOrdemServico relationships")
            .satisfies(e -> assertThat(e.getServicoContabil()).as("check servicoContabil").isEqualTo(actual.getServicoContabil()))
            .satisfies(e -> assertThat(e.getOrdemServico()).as("check ordemServico").isEqualTo(actual.getOrdemServico()));
    }
}
