package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ServicoContabilEmpresaModeloAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEmpresaModeloAllPropertiesEquals(
        ServicoContabilEmpresaModelo expected,
        ServicoContabilEmpresaModelo actual
    ) {
        assertServicoContabilEmpresaModeloAutoGeneratedPropertiesEquals(expected, actual);
        assertServicoContabilEmpresaModeloAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEmpresaModeloAllUpdatablePropertiesEquals(
        ServicoContabilEmpresaModelo expected,
        ServicoContabilEmpresaModelo actual
    ) {
        assertServicoContabilEmpresaModeloUpdatableFieldsEquals(expected, actual);
        assertServicoContabilEmpresaModeloUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEmpresaModeloAutoGeneratedPropertiesEquals(
        ServicoContabilEmpresaModelo expected,
        ServicoContabilEmpresaModelo actual
    ) {
        assertThat(expected)
            .as("Verify ServicoContabilEmpresaModelo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEmpresaModeloUpdatableFieldsEquals(
        ServicoContabilEmpresaModelo expected,
        ServicoContabilEmpresaModelo actual
    ) {
        assertThat(expected)
            .as("Verify ServicoContabilEmpresaModelo relevant properties")
            .satisfies(e -> assertThat(e.getObrigatorio()).as("check obrigatorio").isEqualTo(actual.getObrigatorio()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertServicoContabilEmpresaModeloUpdatableRelationshipsEquals(
        ServicoContabilEmpresaModelo expected,
        ServicoContabilEmpresaModelo actual
    ) {
        assertThat(expected)
            .as("Verify ServicoContabilEmpresaModelo relationships")
            .satisfies(e -> assertThat(e.getEmpresaModelo()).as("check empresaModelo").isEqualTo(actual.getEmpresaModelo()))
            .satisfies(e -> assertThat(e.getServicoContabil()).as("check servicoContabil").isEqualTo(actual.getServicoContabil()));
    }
}
