package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubTarefaRecorrenteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubTarefaRecorrenteAllPropertiesEquals(SubTarefaRecorrente expected, SubTarefaRecorrente actual) {
        assertSubTarefaRecorrenteAutoGeneratedPropertiesEquals(expected, actual);
        assertSubTarefaRecorrenteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubTarefaRecorrenteAllUpdatablePropertiesEquals(SubTarefaRecorrente expected, SubTarefaRecorrente actual) {
        assertSubTarefaRecorrenteUpdatableFieldsEquals(expected, actual);
        assertSubTarefaRecorrenteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubTarefaRecorrenteAutoGeneratedPropertiesEquals(SubTarefaRecorrente expected, SubTarefaRecorrente actual) {
        assertThat(expected)
            .as("Verify SubTarefaRecorrente auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubTarefaRecorrenteUpdatableFieldsEquals(SubTarefaRecorrente expected, SubTarefaRecorrente actual) {
        assertThat(expected)
            .as("Verify SubTarefaRecorrente relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getOrdem()).as("check ordem").isEqualTo(actual.getOrdem()))
            .satisfies(e -> assertThat(e.getConcluida()).as("check concluida").isEqualTo(actual.getConcluida()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubTarefaRecorrenteUpdatableRelationshipsEquals(SubTarefaRecorrente expected, SubTarefaRecorrente actual) {
        assertThat(expected)
            .as("Verify SubTarefaRecorrente relationships")
            .satisfies(
                e ->
                    assertThat(e.getTarefaRecorrenteExecucao())
                        .as("check tarefaRecorrenteExecucao")
                        .isEqualTo(actual.getTarefaRecorrenteExecucao())
            );
    }
}
