package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TarefaRecorrenteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaRecorrenteAllPropertiesEquals(TarefaRecorrente expected, TarefaRecorrente actual) {
        assertTarefaRecorrenteAutoGeneratedPropertiesEquals(expected, actual);
        assertTarefaRecorrenteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaRecorrenteAllUpdatablePropertiesEquals(TarefaRecorrente expected, TarefaRecorrente actual) {
        assertTarefaRecorrenteUpdatableFieldsEquals(expected, actual);
        assertTarefaRecorrenteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaRecorrenteAutoGeneratedPropertiesEquals(TarefaRecorrente expected, TarefaRecorrente actual) {
        assertThat(expected)
            .as("Verify TarefaRecorrente auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaRecorrenteUpdatableFieldsEquals(TarefaRecorrente expected, TarefaRecorrente actual) {
        assertThat(expected)
            .as("Verify TarefaRecorrente relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()))
            .satisfies(e -> assertThat(e.getNotificarCliente()).as("check notificarCliente").isEqualTo(actual.getNotificarCliente()))
            .satisfies(e -> assertThat(e.getNotificarContador()).as("check notificarContador").isEqualTo(actual.getNotificarContador()))
            .satisfies(e -> assertThat(e.getAnoReferencia()).as("check anoReferencia").isEqualTo(actual.getAnoReferencia()))
            .satisfies(e -> assertThat(e.getDataAdmin()).as("check dataAdmin").isEqualTo(actual.getDataAdmin()))
            .satisfies(e -> assertThat(e.getRecorencia()).as("check recorencia").isEqualTo(actual.getRecorencia()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaRecorrenteUpdatableRelationshipsEquals(TarefaRecorrente expected, TarefaRecorrente actual) {
        assertThat(expected)
            .as("Verify TarefaRecorrente relationships")
            .satisfies(
                e ->
                    assertThat(e.getServicoContabilAssinaturaEmpresa())
                        .as("check servicoContabilAssinaturaEmpresa")
                        .isEqualTo(actual.getServicoContabilAssinaturaEmpresa())
            );
    }
}
