package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TarefaRecorrenteEmpresaModeloAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaRecorrenteEmpresaModeloAllPropertiesEquals(
        TarefaRecorrenteEmpresaModelo expected,
        TarefaRecorrenteEmpresaModelo actual
    ) {
        assertTarefaRecorrenteEmpresaModeloAutoGeneratedPropertiesEquals(expected, actual);
        assertTarefaRecorrenteEmpresaModeloAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaRecorrenteEmpresaModeloAllUpdatablePropertiesEquals(
        TarefaRecorrenteEmpresaModelo expected,
        TarefaRecorrenteEmpresaModelo actual
    ) {
        assertTarefaRecorrenteEmpresaModeloUpdatableFieldsEquals(expected, actual);
        assertTarefaRecorrenteEmpresaModeloUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaRecorrenteEmpresaModeloAutoGeneratedPropertiesEquals(
        TarefaRecorrenteEmpresaModelo expected,
        TarefaRecorrenteEmpresaModelo actual
    ) {
        assertThat(expected)
            .as("Verify TarefaRecorrenteEmpresaModelo auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaRecorrenteEmpresaModeloUpdatableFieldsEquals(
        TarefaRecorrenteEmpresaModelo expected,
        TarefaRecorrenteEmpresaModelo actual
    ) {
        assertThat(expected)
            .as("Verify TarefaRecorrenteEmpresaModelo relevant properties")
            .satisfies(e -> assertThat(e.getDiaAdmin()).as("check diaAdmin").isEqualTo(actual.getDiaAdmin()))
            .satisfies(e -> assertThat(e.getMesLegal()).as("check mesLegal").isEqualTo(actual.getMesLegal()))
            .satisfies(e -> assertThat(e.getRecorrencia()).as("check recorrencia").isEqualTo(actual.getRecorrencia()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaRecorrenteEmpresaModeloUpdatableRelationshipsEquals(
        TarefaRecorrenteEmpresaModelo expected,
        TarefaRecorrenteEmpresaModelo actual
    ) {
        assertThat(expected)
            .as("Verify TarefaRecorrenteEmpresaModelo relationships")
            .satisfies(
                e ->
                    assertThat(e.getServicoContabilEmpresaModelo())
                        .as("check servicoContabilEmpresaModelo")
                        .isEqualTo(actual.getServicoContabilEmpresaModelo())
            );
    }
}
