package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TarefaEmpresaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaEmpresaAllPropertiesEquals(TarefaEmpresa expected, TarefaEmpresa actual) {
        assertTarefaEmpresaAutoGeneratedPropertiesEquals(expected, actual);
        assertTarefaEmpresaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaEmpresaAllUpdatablePropertiesEquals(TarefaEmpresa expected, TarefaEmpresa actual) {
        assertTarefaEmpresaUpdatableFieldsEquals(expected, actual);
        assertTarefaEmpresaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaEmpresaAutoGeneratedPropertiesEquals(TarefaEmpresa expected, TarefaEmpresa actual) {
        assertThat(expected)
            .as("Verify TarefaEmpresa auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaEmpresaUpdatableFieldsEquals(TarefaEmpresa expected, TarefaEmpresa actual) {
        assertThat(expected)
            .as("Verify TarefaEmpresa relevant properties")
            .satisfies(e -> assertThat(e.getDataHora()).as("check dataHora").isEqualTo(actual.getDataHora()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTarefaEmpresaUpdatableRelationshipsEquals(TarefaEmpresa expected, TarefaEmpresa actual) {
        assertThat(expected)
            .as("Verify TarefaEmpresa relationships")
            .satisfies(e -> assertThat(e.getEmpresa()).as("check empresa").isEqualTo(actual.getEmpresa()))
            .satisfies(e -> assertThat(e.getContador()).as("check contador").isEqualTo(actual.getContador()))
            .satisfies(e -> assertThat(e.getTarefa()).as("check tarefa").isEqualTo(actual.getTarefa()));
    }
}
