package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TipoDenunciaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDenunciaAllPropertiesEquals(TipoDenuncia expected, TipoDenuncia actual) {
        assertTipoDenunciaAutoGeneratedPropertiesEquals(expected, actual);
        assertTipoDenunciaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDenunciaAllUpdatablePropertiesEquals(TipoDenuncia expected, TipoDenuncia actual) {
        assertTipoDenunciaUpdatableFieldsEquals(expected, actual);
        assertTipoDenunciaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDenunciaAutoGeneratedPropertiesEquals(TipoDenuncia expected, TipoDenuncia actual) {
        assertThat(expected)
            .as("Verify TipoDenuncia auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDenunciaUpdatableFieldsEquals(TipoDenuncia expected, TipoDenuncia actual) {
        assertThat(expected)
            .as("Verify TipoDenuncia relevant properties")
            .satisfies(e -> assertThat(e.getTipo()).as("check tipo").isEqualTo(actual.getTipo()))
            .satisfies(e -> assertThat(e.getDescricao()).as("check descricao").isEqualTo(actual.getDescricao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTipoDenunciaUpdatableRelationshipsEquals(TipoDenuncia expected, TipoDenuncia actual) {}
}
