package com.dobemcontabilidade.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UsuarioGestaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioGestaoAllPropertiesEquals(UsuarioGestao expected, UsuarioGestao actual) {
        assertUsuarioGestaoAutoGeneratedPropertiesEquals(expected, actual);
        assertUsuarioGestaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioGestaoAllUpdatablePropertiesEquals(UsuarioGestao expected, UsuarioGestao actual) {
        assertUsuarioGestaoUpdatableFieldsEquals(expected, actual);
        assertUsuarioGestaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioGestaoAutoGeneratedPropertiesEquals(UsuarioGestao expected, UsuarioGestao actual) {
        assertThat(expected)
            .as("Verify UsuarioGestao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioGestaoUpdatableFieldsEquals(UsuarioGestao expected, UsuarioGestao actual) {
        assertThat(expected)
            .as("Verify UsuarioGestao relevant properties")
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getSenha()).as("check senha").isEqualTo(actual.getSenha()))
            .satisfies(e -> assertThat(e.getToken()).as("check token").isEqualTo(actual.getToken()))
            .satisfies(e -> assertThat(e.getDataHoraAtivacao()).as("check dataHoraAtivacao").isEqualTo(actual.getDataHoraAtivacao()))
            .satisfies(e -> assertThat(e.getDataLimiteAcesso()).as("check dataLimiteAcesso").isEqualTo(actual.getDataLimiteAcesso()))
            .satisfies(e -> assertThat(e.getSituacao()).as("check situacao").isEqualTo(actual.getSituacao()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUsuarioGestaoUpdatableRelationshipsEquals(UsuarioGestao expected, UsuarioGestao actual) {
        assertThat(expected)
            .as("Verify UsuarioGestao relationships")
            .satisfies(e -> assertThat(e.getAdministrador()).as("check administrador").isEqualTo(actual.getAdministrador()));
    }
}
