# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: erpdobemcontabilidade
services:
  app:
    image: dobemcontabilidade/erpdobemcontabilidade
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=dev,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/erpDobemcontabilidade
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://postgresql:5432/erpDobemcontabilidade
    ports:
      - 127.0.0.1:8080:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      postgresql:
        condition: service_healthy
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dobemcontabilidade.com
      PGADMIN_DEFAULT_PASSWORD: senhaAdmin
    ports:
      - '9000:80'
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    extends:
      file: ./postgresql.yml
      service: 'postgresql'
